apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: mytaskrun2
spec:
  serviceAccountName: tekton-service-account
  taskRef:
    name: build-docker-image-from-git-source
  params:
    - name: namespace
      value: "default"
    - name: image-version
      value: "1234"
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: training-tekton-git
    outputs:
      - name: builtImage
        resourceRef:
          name: training-tekton-image