---
# Source: nfs-client-provisioner/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Tiller
    release: nfs
  name: nfs-client
provisioner: cluster.local/nfs-nfs-client-provisioner
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  archiveOnDelete: "true"

---
# Source: nfs-client-provisioner/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Tiller
    release: nfs
  name: nfs-nfs-client-provisioner
---
# Source: nfs-client-provisioner/templates/clusterrole.yaml

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Tiller
    release: nfs
  name: nfs-nfs-client-provisioner-runner
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'


---
# Source: nfs-client-provisioner/templates/clusterrolebinding.yaml

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Tiller
    release: nfs
  name: run-nfs-nfs-client-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-nfs-client-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: nfs-nfs-client-provisioner-runner
  apiGroup: rbac.authorization.k8s.io

---
# Source: nfs-client-provisioner/templates/role.yaml

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Tiller
    release: nfs
  name: leader-locking-nfs-nfs-client-provisioner
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
# Source: nfs-client-provisioner/templates/rolebinding.yaml

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Tiller
    release: nfs
  name: leader-locking-nfs-nfs-client-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-nfs-client-provisioner
    namespace: default
roleRef:
  kind: Role
  name: leader-locking-nfs-nfs-client-provisioner
  apiGroup: rbac.authorization.k8s.io

---
# Source: nfs-client-provisioner/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.8
    heritage: Tiller
    release: nfs
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
      release: nfs
  template:
    metadata:
      annotations:
      labels:
        app: nfs-client-provisioner
        release: nfs
    spec:
      serviceAccountName: nfs-nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: "quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: cluster.local/nfs-nfs-client-provisioner
            - name: NFS_SERVER
              value: ubuntu
            - name: NFS_PATH
              value: /storage/nfs
      volumes:
        - name: nfs-client-root
          nfs:
            server: ubuntu
            path: /storage/nfs

---
# Source: nfs-client-provisioner/templates/persistentvolume.yaml

---
# Source: nfs-client-provisioner/templates/persistentvolumeclaim.yaml

---
# Source: nfs-client-provisioner/templates/podsecuritypolicy.yaml


