apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-liberty
  namespace: default
  labels:
    app: open-liberty
spec:
  selector:
    matchLabels:
      app: open-liberty
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "30%"
      maxSurge: "90%"
  template:
    metadata:
      labels:
        app: open-liberty
        version: current
    spec:
      containers:
      - name: open-liberty
        image: open-liberty:full
        imagePullPolicy: IfNotPresent 
        livenessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 5
          periodSeconds: 1
          successThreshold: 1 
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 0
          periodSeconds: 1
          successThreshold: 1 
          failureThreshold: 1
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "150m"
            memory: "150Mi"
          limits:
            cpu: "1"
            memory: "500Mi"
        env:
          - name: PORT
            value : "3000"
          - name: APPLICATION_NAME
            value: open-liberty
          - name: BACKEND_URL
            value: http://open-liberty-backend-service.default.svc:3000/api
