apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-init
  namespace: default
  labels:
    app: nginx-demo
spec:
  selector:
    matchLabels:
      app: nginx-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80

       # Volume mapped into the nginx pod
        volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html

      # This container is run during pod initialization
      initContainers:

      # Sleep for 2 Seconds
      - name: sleep-1
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo sleep-1 start; sleep 2;echo sleep-1 complete;']

      # Sleep again for 2 Seconds
      - name: sleep-2
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo sleep-2 start; sleep 2;echo sleep-2 complete;']
      - name: install
        image: busybox

        # Download index.html and store into work-dir
        command:
        - wget
        - "-O"
        - "/work-dir/index.html"
        - http://kubernetes.io
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"

      dnsPolicy: Default
      volumes:
      - name: workdir
        emptyDir: {}